# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/Pc/CALISMALARIM/PyQt5_Projeler/Mask-to-json-to-mask/mask_json_convert.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_converter(object):
    def setupUi(self, converter):
        converter.setObjectName("converter")
        converter.resize(700, 500)
        converter.setMinimumSize(QtCore.QSize(700, 500))
        converter.setMaximumSize(QtCore.QSize(700, 536))
        self.centralwidget = QtWidgets.QWidget(converter)
        self.centralwidget.setStyleSheet("background-image: url(:/icons/images/background.jpg);")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.page_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setVerticalSpacing(50)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.Buton_mask = QtWidgets.QPushButton(self.page_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.Buton_mask.setFont(font)
        self.Buton_mask.setObjectName("Buton_mask")
        self.horizontalLayout.addWidget(self.Buton_mask)
        self.gridLayout_2.addLayout(self.horizontalLayout, 1, 1, 1, 1)
        self.lineEdit_mask = QtWidgets.QLineEdit(self.page_3)
        self.lineEdit_mask.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_mask.setObjectName("lineEdit_mask")
        self.gridLayout_2.addWidget(self.lineEdit_mask, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.page_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.page_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 2, 0, 1, 1)
        self.lineEdit_json = QtWidgets.QLineEdit(self.page_3)
        self.lineEdit_json.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_json.setObjectName("lineEdit_json")
        self.gridLayout_2.addWidget(self.lineEdit_json, 2, 1, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(-1, 0, 0, -1)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem1 = QtWidgets.QSpacerItem(250, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.pushButton = QtWidgets.QPushButton(self.page_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_6.addWidget(self.pushButton)
        self.gridLayout_2.addLayout(self.horizontalLayout_6, 5, 1, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.Buton_json = QtWidgets.QPushButton(self.page_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.Buton_json.setFont(font)
        self.Buton_json.setObjectName("Buton_json")
        self.horizontalLayout_2.addWidget(self.Buton_json)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 3, 1, 1, 1)
        self.Start = QtWidgets.QPushButton(self.page_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.Start.setFont(font)
        self.Start.setObjectName("Start")
        self.gridLayout_2.addWidget(self.Start, 4, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 1, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.stackedWidget.addWidget(self.page_4)
        self.gridLayout.addWidget(self.stackedWidget, 0, 0, 1, 1)
        converter.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(converter)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 700, 26))
        self.menubar.setObjectName("menubar")
        self.menuMod_ller = QtWidgets.QMenu(self.menubar)
        self.menuMod_ller.setObjectName("menuMod_ller")
        converter.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(converter)
        self.statusbar.setObjectName("statusbar")
        converter.setStatusBar(self.statusbar)
        self.actionMask_to_JSON = QtWidgets.QAction(converter)
        self.actionMask_to_JSON.setObjectName("actionMask_to_JSON")
        self.actionJSON_to_Mask = QtWidgets.QAction(converter)
        self.actionJSON_to_Mask.setObjectName("actionJSON_to_Mask")
        self.menuMod_ller.addAction(self.actionMask_to_JSON)
        self.menuMod_ller.addAction(self.actionJSON_to_Mask)
        self.menubar.addAction(self.menuMod_ller.menuAction())

        self.retranslateUi(converter)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(converter)

    def retranslateUi(self, converter):
        _translate = QtCore.QCoreApplication.translate
        converter.setWindowTitle(_translate("converter", "Converter"))
        self.Buton_mask.setText(_translate("converter", "Ekle"))
        self.label.setText(_translate("converter", "Mask Path"))
        self.label_2.setText(_translate("converter", "JSON Path"))
        self.pushButton.setText(_translate("converter", "JSON to Mask >>"))
        self.Buton_json.setText(_translate("converter", "Ekle"))
        self.Start.setText(_translate("converter", "BAŞLAT"))
        self.menuMod_ller.setTitle(_translate("converter", "Modüller"))
        self.actionMask_to_JSON.setText(_translate("converter", "Mask to JSON"))
        self.actionJSON_to_Mask.setText(_translate("converter", "JSON to Mask"))

import icon_rc
